"""'comments'

Revision ID: 688bfd1cd167
Revises: 
Create Date: 2023-09-01 18:08:25.569502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688bfd1cd167'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Veiculo',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Tipo', sa.Integer(), nullable=True),
    sa.Column('Cor', sa.String(length=70), nullable=True),
    sa.Column('Marca', sa.String(length=70), nullable=True),
    sa.Column('Modelo', sa.String(length=70), nullable=True),
    sa.Column('AnoFabricacao', sa.String(length=20), nullable=True),
    sa.Column('Novo', sa.Boolean(), nullable=True),
    sa.Column('KmRodados', sa.Integer(), nullable=True),
    sa.Column('Leilao', sa.Boolean(), nullable=True),
    sa.Column('Parcela', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Veiculo')
    # ### end Alembic commands ###
