"""empty message

Revision ID: f2c1072d4394
Revises: 688bfd1cd167
Create Date: 2023-09-04 16:10:03.673858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2c1072d4394'
down_revision = '688bfd1cd167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Veiculos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Tipo', sa.Integer(), nullable=True),
    sa.Column('Cor', sa.String(length=70), nullable=True),
    sa.Column('Marca', sa.String(length=70), nullable=True),
    sa.Column('Modelo', sa.String(length=70), nullable=True),
    sa.Column('AnoFabricacao', sa.String(length=20), nullable=True),
    sa.Column('Novo', sa.Boolean(), nullable=True),
    sa.Column('KmRodados', sa.Integer(), nullable=True),
    sa.Column('Leilao', sa.Boolean(), nullable=True),
    sa.Column('Parcela', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculos',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Tipo', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Cor', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('Marca', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('Modelo', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('AnoFabricacao', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Novo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('KmRodados', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Leilao', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('Parcela', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
